Update log format
nginxinc/nginx-asg-sync pull request #42
Opened 2020-09-21 11:30 UTC by LorcanMcVeigh

### Proposed changes
update log format from 
`2020/04/10 21:13:43 Updated HTTP servers of {backend2 80 asg-sync-4-WebserverGroup2-B07B6PPXO49Y http 0xc0000a50e0 0xc0000a50e8 10s 0s}; Added: [{ID:0 Server:172.31.26.57:80 MaxConns:0xc0000a50e0 MaxFails:0xc0000a50e8 FailTimeout:10s SlowStart:0s Route: Backup:<nil> Down:<nil> Drain:false Weight:<nil> Service:}], Removed: [], Updated: []`
To new format 
`2020/04/10 21:13:43 Updated HTTP servers of backend2 for group asg-sync-4-WebserverGroup2-B07B6PPXO49Y: Added: [172.31.26.57:80,172.31.26.61:80], Removed: [], Updated: []`

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-asg-sync/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

2020-09-22 13:05 UTC, Dean-Coakley requested changes
Thanks for including a sample output in the PR description. - That's helpful!

2020-09-22 13:05 UTC, Dean-Coakley commented on cmd/sync/main.go
> +					log.Printf("Updated HTTP servers of %v for group %v ; Added: %+v, Removed: %+v, Updated: %+v", upstream.Name, upstream.ScalingGroup, getUpstreamServerAddress(added), getUpstreamServerAddress(rem
This line is extremely long. Consider one of the following suggestions:

```suggestion
					log.Printf("Updated HTTP servers of %v for group %v ; Added: %+v, Removed: %+v, Updated: %+v",
						upstream.Name, upstream.ScalingGroup, getUpstreamServerAddress(added), getUpstreamServerAddress(removed), getUpstreamServerAddress(updated))
```

or

```suggestion
					addedAddresses := getUpstreamServerAddress(added)
					removedAddresses := getUpstreamServerAddress(removed)
					updatedAddresses := getUpstreamServerAddress(updated)
					log.Printf("Updated HTTP servers of %v for group %v ; Added: %+v, Removed: %+v, Updated: %+v",
						upstream.Name, upstream.ScalingGroup, addedAddresses, removedAddresses, updatedAddresses)
```

or

```suggestion
					addedAddresses, removedAddresses, updatedAddresses := getUpstreamServerAddresses(added, removed, updated)
					log.Printf("Updated HTTP servers of %v for group %v ; Added: %+v, Removed: %+v, Updated: %+v",
						upstream.Name, upstream.ScalingGroup, addedAddresses, removedAddresses, updatedAddresses)
```

2020-09-22 13:05 UTC, Dean-Coakley commented on cmd/sync/main.go
> +func getUpstreamServerAddress(server []nginx.UpstreamServer) []string {
Because you return a slice your return value should be plural.

```suggestion
func getUpstreamServerAddresses(server []nginx.UpstreamServer) []string {
```

2020-09-22 13:05 UTC, Dean-Coakley commented on cmd/sync/main.go
> +func getStreamUpstreamServerAddress(server []nginx.StreamUpstreamServer) []string {
Because you return a slice your return value should be plural

```suggestion
func getStreamUpstreamServerAddresses(server []nginx.StreamUpstreamServer) []string {
```

2020-09-22 13:05 UTC, Dean-Coakley commented on cmd/sync/main.go
> +	return StreamUpstreamServerAddr
`streamUpstreamServerAddr` was mistakenly exported?

```suggestion
	var streamUpstreamServerAddr []string
	for _, s := range server {
		streamUpstreamServerAddr = append(streamUpstreamServerAddr, s.Server)
	}
	return streamUpstreamServerAddr
```

2020-09-22 13:07 UTC, Dean-Coakley commented on cmd/sync/main.go
> +func getUpstreamServerAddress(server []nginx.UpstreamServer) []string {
@lucacome Should this func be renamed to `getUpstreamServerEndpoints` or am I spending too much time with Kubernetes? 😅

2020-09-22 15:01 UTC, LorcanMcVeigh commented on cmd/sync/main.go
> +	return StreamUpstreamServerAddr
yes

2020-09-28 15:42 UTC, lucacome commented on cmd/sync/main.go
> +func getUpstreamServerAddress(server []nginx.UpstreamServer) []string {
I think `Addresses` is good 😄

2020-09-28 15:45 UTC, lucacome approved these changes

2020-09-29 15:08 UTC, Dean-Coakley approved these changes

2020-09-29 15:08 UTC, Dean-Coakley commented on cmd/sync/main.go
> +func getUpstreamServerAddress(server []nginx.UpstreamServer) []string {
```suggestion
func getUpstreamServerAddresses(server []nginx.UpstreamServer) []string {
```

2020-09-29 15:08 UTC, Dean-Coakley commented on cmd/sync/main.go
> +					log.Printf("Updated Stream servers of %v for group %v ; Added: %+v, Removed: %+v, Updated: %+v", upstream.Name, upstream.ScalingGroup, getStreamUpstreamServerAddress(added), getStreamUpstreamSer
I recommend making the same change as with HTTP to reduce line length.

(something like:)
```suggestion
					addedAddresses := getStreamUpstreamServerAddress(added)
					removedAddresses := getStreamUpstreamServerAddress(removed)
					updatedAddresses := getStreamUpstreamServerAddress(updated)
					log.Printf("Updated Stream servers of %v for group %v ; Added: %+v, Removed: %+v, Updated: %+v",
						upstream.Name, upstream.ScalingGroup, addedAddresses, removedAddresses, updatedAddresses
```

2020-09-29 15:41 UTC, Dean-Coakley approved these changes

2020-09-29 15:43 UTC, merged